-- Browser access goes through authenticated application APIs.
-- The server database owner retains access; anon/authenticated Supabase roles have no policies.
ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Game" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Participant" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Question" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "GameQuestion" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Answer" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "GameResult" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "GuestSession" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Admin" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AdminSession" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "GameCommand" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RealtimeConnection" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AnswerSubmission" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "GameEventRecord" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "QuestionImage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PersonalResult" ENABLE ROW LEVEL SECURITY;
